# lists----------------------------------------
//GET all lists for idUser
GET http://localhost:3000/api/lists/1

###

//GET list for idUser/idList;
GET http://localhost:3000/api/lists/1/13



###
//CREATE list, idUser/idList; 
POST http://localhost:3000/api/lists/create
Content-Type: application/json

{
    "title": "MERCA",
    "descriptions": " madrid",
    "idUser": 2
}

###
//DELETE list, idUser/idList
DELETE http://localhost:3000/api/lists/delete/2/13

###

//UPDATE list, idUser/idList
PUT http://localhost:3000/api/lists/update
Content-Type: application/json

{
    "title": "UGTttt",
    "descriptions": "graddddo",
    "idUser":1,
    "idList":12
}
###
# Persons----------------------------------------------

// persons of idUser and idList
GET http://localhost:3000/api/persons/userId/1/listId/1